### ISSUE TITLE
NANOOS sensorml.py module

### ISSUE THREAD

**Issue by emiliom** [ioos/sensorml2iso#1]
@mwengren, I've just uploaded into https://github.com/nanoos-pnw/ioos-ws the core/lean sensorml processing module ([sensorml.py](https://github.com/nanoos-pnw/ioos-ws/blob/master/sensorml.py)) we use operationally. It's basically the `get_stations_df` function from our notebook (plus its dependencies and helpers), except that's the code we actually use, so it's more guaranteed to work and be up to date, and you can drop it as-is into your `sensorml2iso` repo.

For your task of creating an ISO XML, you really don't need the extra geospatial goodness that's in my notebook; you have `geopandas` and `shapely` imports in your [sensorml2iso.py](https://github.com/mwengren/sensorml2iso/blob/master/sensorml2iso/sensorml2iso.py), but you won't need them. `get_stations_df` does the heavy lifting and returns a pandas DataFrame. If you need to parse additional attributes from the SensorML, we can just modify `get_stations_df` to do so. FYI, I don't try to parse "everything" from the SensorML; just attributes that I felt were important, including ones that reflect IOOS SensorML conventions/requirements (though likely not all of them).

Hope that helps.

**Comment by mwengren** [comment]
@emiliom, thanks, i missed this earlier as I had my head down trying to get some filtering and the Jinja2 template working.  I'll be cleaning up the imports next and will discard the unneeded ones.  flake8 warned me on those (until I excluded those errors in the Travis build that is).  

I am enjoying the Pandas code though since it's my first time using it.  I would like to dabble with Geopandas as well but this is probably not the place.  I ran into an issue with conda in Windows that prevented me from writing out to Geopackage. I think @ocefpaf has that on his radar screen for a fix someday though. Thanks again.

**Comment by emiliom** [comment]
Yeah, the geopackage stuff is completely unnecessary for your sensorml2iso application.

FYI, I'm working on tutorial materials for an event at my university taking place in a couple of weeks:
https://geohackweek.github.io/
My materials are specifically on FOSS geospatial ("vector") processing and tools in Python, emphasizing GeoPandas. You'll probably like that stuff once it's ready (assuming I do a decent job!).

Glad to hear you're liking Pandas! It's really core Python infrastructure at this point, for the kind of stuff we do.

Ok, back to the grind ...

**Comment by emiliom** [comment]
@mwengren, it looks like you can close this issue. Just a suggestion, while I'm looking around here.
